vich_uploader:
    db_driver: orm
    mappings:
        videos:
            uri_prefix: /uploads/videos'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
            upload_destination: '%kernel.project_dir%/public/uploads/videos'

        articles:
            uri_prefix: /uploads/article
            upload_destination: '%kernel.project_dir%/public/uploads/article'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer