version: '3.8'

services: 
  app:
    build:
      context: .  # Contexte de construction, remonte d'un niveau pour accéder au Dockerfile
      dockerfile: Dockerfile  # Assurez-vous que le Dockerfile est dans le répertoire parent

    volumes:
      - ../projet:/workspaces/projet  # Mount the project folder into the container

    env_file:
      - ../projet/.env.local  # Charge les variables d'environnement depuis le fichier .env.local

    ports:
      - "8080:80"  # Redirige le port 80 du conteneur vers le port 8080 de l'hôte

  db:
    image: mariadb:10.4  
    restart: unless-stopped  
    volumes:
      - db_data:/var/lib/mysql  
    environment:
      MYSQL_ROOT_PASSWORD: mourad  
      MYSQL_DATABASE: municipaliter  
      MYSQL_USER: mourad  
      MYSQL_PASSWORD: mourad  

volumes:
  db_data:  